### ISSUE TITLE
Always overrides poise-service provider 

### ISSUE THREAD

**Issue by johnbellone** [poise/poise-service-runit#1]
It seems that this always overrides the ```node['poise-service']['provider'] = 'auto'``` which I do not think should be the case. I think this should require either an explicit ```node.default['poise-service']['provider'] = 'runit'``` in a recipe or an override in an attributes file.

Perhaps the answer here is to add a recipe in poise-service-runit which does the above?

**Comment by johnbellone** [comment]
An example can be see [in my develop branch of Consul cookbook](https://github.com/johnbellone/consul-cookbook/tree/develop).

**Comment by coderanger** [comment]
So the intent is that a library/generic cookbook should only depend on `poise-service`. The backend plugin cookbooks are effectively end-point policy and so should only be pulled by the final admin. The most common case is that when pulling in a plugin like this, you also want it to be the default. If you want to set per-service providers that requires additional config anyway (role or wrapper cookbook) so it is pretty much the same amount of work either way.
