### ISSUE TITLE
Allow passing supplementary groups to chpst

### ISSUE THREAD

**Issue by benwtr** [poise/poise-service-runit#6]
From `(8) chpst`:

> -u [:]user[:group]
> setuidgid. Set uid and gid to the user’s uid and gid, as found in /etc/passwd. If user is followed by a colon and a group, set the gid to group’s gid, as found in /etc/group, instead of user’s gid. If group consists of a colon-separated list of group names, chpst sets the group ids of all listed groups. If user is prefixed with a colon, the user and all group arguments are interpreted as uid and gids respectivly, and not looked up in the password or group file. All initial supplementary groups are removed.

In other words, when a process starts under chpst, any groups that the user is a member of that aren't explicitly passed in with `-u user:group1:group2:..` are removed.

It would be great to have a way to pass in additional groups here.

**Comment by coderanger** [comment]
Hmm, so part of the conceit of `poise-service` is that services only get a user and things always run as that user's primary group. Secondary groups are so rarely used for services that I didn't want to add an abstraction layer for that. You can override the template for the `run` script and add it there, would that be enough?

**Comment by benwtr** [comment]
I see. Yeah, overriding the template would be fine. 

Will setting a `template` attribute on `poise_service` with `provider :runit` override the template for the run script?

**Comment by coderanger** [comment]
Example code I shared on Slack

```ruby
# libraries/default.rb
class MyRunit < PoiseService::Runit::Provider
  provides(:my_runit)
  def service_resource
    super.tap {|r| r.cookbook 'my-cookbook' }
  end
end

# recipe code
poise_service 'whatever' do
  provider :my_runit
end
```

To anyone finding this in the future, you'll have to copy all (or at least most) of the templates from this cookbook to your own and then modify them. The underlying `runit_service` resource doesn't support reading just the run template from a given cookbook.
